# Generated by Django 4.2.3 on 2023-07-28 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('m', 'm'), ('f', 'f')], max_length=128)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mail', models.EmailField(max_length=254)),
                ('dept', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'new',
            },
        ),
    ]
